version: "3.3"

networks:
  proxy:
    external: true

services:

  folding-at-home:
    image: yurinnick/folding-at-home
    container_name: folding-at-home
    networks:
      - proxy
    command: ["--allow=0/0", "--web-allow=0/0"] # Allow connections from non-localhost ip addresses
    environment:
      - USER=plateofash
      - TEAM=0
      - ENABLE_GPU=false
      - ENABLE_SMP=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.folding-at-home.entrypoints=http"
      - "traefik.http.routers.folding-at-home.rule=Host(`folding.${DOMAIN}`)"
      - "traefik.http.services.folding-at-home.loadbalancer.server.port=7396"

