version: "3"

networks:
  traefik_public:
    external: true

services:

  rtorrent:
    image: linuxserver/rutorrent:latest
    env_file : ${ENV_DIR}/autopirate/rtorrent.env
    ports:
      - 51413:51413
      - 5000:5000
      - 6881:6881/udp
    volumes:
      - ${DATA_DIR}/autopirate/rtorrent:/config
      - ${MEDIA_DIR}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rtorrent.entrypoints=http"
      - "traefik.http.routers.rtorrent.middlewares=secure"
      - "traefik.http.routers.rtorrent.rule=Host(`rtorrent.${DOMAIN}`)"
      - "traefik.http.services.rtorrent.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  sonarr:
    image: linuxserver/sonarr:latest
    env_file : ${ENV_DIR}/autopirate/sonarr.env
    volumes:
      - ${DATA_DIR}/autopirate/sonarr:/config
      - ${MEDIA_DIR}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.middlewares=secure"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  radarr:
    image: linuxserver/radarr:latest
    env_file : ${ENV_DIR}/autopirate/radarr.env
    volumes:
      - ${DATA_DIR}/autopirate/radarr:/config
      - ${MEDIA_DIR}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.middlewares=secure"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  lidarr:
    image: linuxserver/lidarr:latest
    env_file : ${ENV_DIR}/autopirate/lidarr.env
    volumes:
      - ${DATA_DIR}/autopirate/lidarr:/config
      - ${MEDIA_DIR}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.entrypoints=http"
      - "traefik.http.routers.lidarr.middlewares=secure"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  nzbget:
    image: linuxserver/nzbget
    env_file : ${ENV_DIR}/autopirate/nzbget.env
    volumes:
      - ${DATA_DIR}/autopirate/nzbget:/config
      - ${MEDIA_DIR}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=http"
      - "traefik.http.routers.nzbget.middlewares=secure"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.${DOMAIN}`)"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  jackett:
    image: linuxserver/jackett:latest
    env_file : ${ENV_DIR}/autopirate/jackett.env
    volumes:
      - ${DATA_DIR}/autopirate/jackett:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.entrypoints=http"
      - "traefik.http.routers.jackett.middlewares=secure"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    env_file : ${ENV_DIR}/autopirate/lazylibrarian.env
    volumes:
      - ${DATA_DIR}/autopirate/lazylibrarian:/config
      - ${MEDIA_DIR}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lazylibrarian.entrypoints=http"
      - "traefik.http.routers.lazylibrarian.middlewares=secure"
      - "traefik.http.routers.lazylibrarian.rule=Host(`lazylibrarian.${DOMAIN}`)"
      - "traefik.http.services.lazylibrarian.loadbalancer.server.port=5299"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  calibre:
    image: linuxserver/calibre:latest
    env_file: ${ENV_DIR}/autopirate/calibre.env
    volumes:
      - ${MEDIA_DIR}/ebooks/calibre/:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.entrypoints=http"
      - "traefik.http.routers.calibre.middlewares=secure"
      - "traefik.http.routers.calibre.rule=Host(`calibre.${DOMAIN}`)"
      - "traefik.http.services.calibre.loadbalancer.server.port=8081"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public

  jellyfin:
    image: linuxserver/jellyfin:latest
    env_file: ${ENV_DIR}/autopirate/jellyfin.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/autopirate/jellyfin:/config
      - ${CACHE_DIR}/autopirate/jellyfin:/cache
      - ${MEDIA_DIR}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.middlewares=secure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=traefik_public"
    networks:
      - default
      - traefik_public
