version: "2.4"

networks:
  proxy:
    external: true

services:

  folding-at-home:
    image: yurinnick/folding-at-home
    container_name: folding-at-home
    networks:
      - proxy
    command: ["--allow=0/0", "--web-allow=0/0"] # Allow connections from non-localhost ip addresses
    volumes:
      - ${DATA_DIR}/folding:/opt/fahclient/work
    environment:
      - USER=plateofash
      - TEAM=0
      - ENABLE_GPU=false
      - ENABLE_SMP=true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"      
      - "traefik.http.routers.folding-at-home.rule=Host(`folding.${DOMAIN}`)"
      - "traefik.http.services.folding-at-home.loadbalancer.server.port=7396"
      - "traefik.http.services.folding-at-home.loadbalancer.server.scheme=http"
      - "traefik.http.services.folding-at-home.loadbalancer.passhostheader=true"  
      - "traefik.http.routers.folding-at-home.middlewares=auth"
      - "traefik.http.middlewares.auth.forwardauth.address=http://organizr/api/?v1/auth&group=0"
    cpus: 2 # Allocate 2/8 CPUs (25%)
    cpu_shares: 64 # Limit shares to ~6%, It will only dip down if other processes need resources
    mem_limit: 512M
