version: "3.3"

networks:
  proxy:
    external: true
  shared-postgres:
    external: true

services:

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    environment:
      - REDIS_PASSWORD=${RANDOM_PASSWORD}
    restart: always
    networks:
      - default

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-redis
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${RANDOM_PASSWORD}
    volumes:
      - ${DATA_DIR}/nextcloud/app:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=http"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    networks:
      - proxy
      - shared-postgres
      - default
