services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/nzbget:/config
      - ./downloads:/downloads
    ports:
      - "6789:6789"
    restart: unless-stopped
    networks:
      - arrnet

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
    networks:
      - arrnet

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/sonarr:/config
      - ./downloads:/downloads
      - ./media/tv:/tv
    ports:
      - "8989:8989"
    depends_on:
      - nzbget
      - jackett
    restart: unless-stopped
    networks:
      - arrnet

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/radarr:/config
      - ./downloads:/downloads
      - ./media/movies:/movies
    ports:
      - "7878:7878"
    depends_on:
      - nzbget
      - jackett
    restart: unless-stopped
    networks:
      - arrnet

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - JELLYFIN_PublishedServerUrl=
    volumes:
      - ./config/jellyfin:/config
      - ./config/jellyfin/cache:/cache
      - ./media/tv:/media/tv
      - ./media/movies:/media/movies
      - ./media/music:/media/music
    ports:
      - "8096:8096"
      - "8920:8920"
    restart: unless-stopped
    networks:
      - arrnet

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PORT=5055
    volumes:
      - ./config/jellyseerr:/app/config
    ports:
      - "5055:5055"
    depends_on:
      - jellyfin
      - sonarr
      - radarr
    restart: unless-stopped
    networks:
      - arrnet

networks:
  arrnet:
    driver: bridge
