services:

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8096:8096" # Jellyfin
    env_file:
      - ./vpn.env

  nzbget:
    image: ghcr.io/hotio/nzbget
    container_name: nzbget
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/nzbget:/config
      - ./data/usenet:/data/usenet
    depends_on:
      - gluetun
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/prowlarr:/config
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    depends_on:
      - nzbget
      - prowlarr
      - gluetun
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    depends_on:
      - nzbget
      - prowlarr
      - gluetun
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - JELLYFIN_PublishedServerUrl=
    volumes:
      - ./config/jellyfin:/config
      - ./config/jellyfin/cache:/cache
      - ./data/media:/data/media
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: jellyseerr
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PORT=5055
    volumes:
      - ./config/jellyseerr:/app/config
    depends_on:
      - jellyfin
      - sonarr
      - radarr
      - gluetun
    restart: unless-stopped

  curl:
    image: curlimages/curl
    network_mode: "service:gluetun"
    entrypoint: ["curl"]
    command: ["icanhazip.com"]
