services:

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8096:8096" # Jellyfin
      - "5055:5055" # Jellyseerr
      - "9696:9696" # Prowlarr
      - "8989:8989" # Sonarr
      - "7878:7878" # Radarr
      - "6789:6789" # NZBGet
    env_file:
      - ./vpn.env

  # headscale:
  #   image: tailscale/tailscale:stable
  #   hostname: arrnet
  #   depends_on:
  #     - gluetun
  #   network_mode: service:gluetun   # Share network with Gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun
  #   volumes:
  #     - ./config/tailscale:/var/lib/tailscale
  #   environment:
  #     - TS_AUTHKEY=tskey-auth-xxxxxxxx
  #     - TS_LOGIN_SERVER=https://headscale.example.com
  #   command: tailscaled

  nzbget:
    image: ghcr.io/hotio/nzbget
    container_name: nzbget
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/nzbget:/config
      - ./data/usenet:/data/usenet
    depends_on:
      - gluetun
    restart: unless-stopped

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/prowlarr:/config
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    depends_on:
      - nzbget
      - prowlarr
      - gluetun
    restart: unless-stopped

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    depends_on:
      - nzbget
      - prowlarr
      - gluetun
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    network_mode: service:gluetun
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - JELLYFIN_PublishedServerUrl=
    volumes:
      - ./config/jellyfin:/config
      - ./config/jellyfin/cache:/cache
      - ./data/media:/data/media
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: jellyseerr
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ:-Etc/UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - PORT=5055
    volumes:
      - ./config/jellyseerr:/app/config
    depends_on:
      - jellyfin
      - sonarr
      - radarr
      - gluetun
    restart: unless-stopped

  curl:
    image: curlimages/curl
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    entrypoint: ["curl"]
    command: ["icanhazip.com"]
