# Following: https://www.reddit.com/r/Tailscale/comments/104y6nq/docker_tailscale_and_caddy_with_https_a_love_story/
version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - nginx_data:/usr/share/nginx/html

volumes:
  nginx_data:
    driver: rclone
    driver_opts:
      remote: 'backblaze:homelab-data-backup/nginx_data'
