#!/bin/bash

if [ $(id -u) -ne 0 ]; then
    echo "Script must be run using sudo"
    exit 1
fi

apt-get update && apt-get upgrade

# Install docker & docker compose
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add --
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt-get update
apt-get install -y \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-compose


if ! getent group docker; then
    groupadd docker
    usermod -aG docker ${SUDO_USER:-$USER}
    newgrp docker
fi

