## traefik.yml

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false

accessLog:
  filePath: "/logs/access.log"

log:
  level: DEBUG

# Entrypoint configuration to be updated with HTTPS
entryPoints:
  http:
    address: ":80"

# API and dashboard configuration
api:
  insecure: true
