version: "3"

services:

  autobackup:
    image: mannkind/borg-rclone-autobackup
    container_name: backup
    restart: unless-stopped
    env_file: ${ENV_DIR}/backup/borg.env
    volumes:
      - ${DATA_DIR}:/data:ro
      - ${LOCAL_BACKUP_DIR}:/backups
