version: "3"

services:

  autobackup:
    image: mannkind/borg-rclone-autobackup
    container_name: backup
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}:/data:ro
      - ${LOCAL_BACKUP_DIR}:/backups
    environment:
      - BACKUP_NAME=homelab
      - BACKUP_LOCATION=${BACKUP_LOCATION}
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE}
      - BACKUP_ENCRYPTION_KEY=${BACKUP_ENCRYPTION_KEY}
      - BACKUP_PRUNE=--keep-daily=${KEEP_DAILY} --keep-weekly=${KEEP_WEEKLY}
      - B2_ID=${B2_ID}
      - B2_KEY=${B2_KEY}
