version: "3.3"

networks:
  traefik_public:
    external: true

services:

  jupyter: # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html
    image: jupyter/tensorflow-notebook
    container_name: jupyter
    command: ["start-notebook.sh", "--NotebookApp.password=${JUPYTER_TOKEN}"]
    env_file: ${ENV_DIR}/jupyter/jupyter.env
    restart: unless-stopped
    user: root
    volumes:
      - ${DATA_DIR}/jupyter:/home/jovyan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.entrypoints=http"
      - "traefik.http.routers.jupyter.rule=Host(`jupyter.${DOMAIN}`)"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
      - "traefik.http.routers.jupyter.middlewares=secure"
    networks:
      - traefik_public
