- name: Install Docker on remote host
  hosts: localmachines
  become: true

  pre_tasks:
    - name: Create a new user
      user:
        name: docker
        state: present
        create_home: true
        generate_ssh_key: true

  roles:
    - name: geerlingguy.docker
      vars:
        docker_edition: ce
        docker_packages_state: present
        docker_service_manage: true
        docker_service_state: started
        docker_service_enabled: true
        docker_users:
          - docker
