version: "3.3"

networks:
  proxy:
    external: true
  database:
    external: true

services:

# Traefik frontend router, will handle all requests sent to server and send to correct container.
  traefik:
    image: traefik:v2.0
    container_name: traefik
    networks:
      - proxy
    ports:
      - 80:80
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

# Shared postgres database for applications that don't require standalone database server.
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ${DATA_DIR}/shared-postgres:/var/lib/postgresql/data
      - ./create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh:ro
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${NEXTCLOUD_DB}:${NEXTCLOUD_DB_PASSWORD},${TTRS_DB}:${TTRS_DB_PASSWORD}
      - POSTGRES_PASSWORD=${SHARED_POSTGRES_PASSWORD}
    networks:
      - database
