version: "3.3"

networks:
  traefik_public:
    external: true
  database:
    external: true

services:

  freshrss:
      image: freshrss/freshrss
      restart: unless-stopped
      env_file: ${ENV_DIR}/freshrss/freshrss.env
      volumes:
        - ${DATA_DIR}/freshrss/data:/var/www/FreshRSS/data
        - ${DATA_DIR}/freshrss/extensions:/var/www/FreshRSS/extensions
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.freshrss.entrypoints=http"
        - "traefik.http.routers.freshrss.rule=Host(`news.${DOMAIN}`)"
        - "traefik.http.services.freshrss.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik_public"
      networks:
        - traefik_public
        - database
