{
 "title": "Adguard Exporter",
 "description": "This is a Adguard dashboard when using the https://github.com/ebrianne/adguard-exporter Prometheus exporter",
 "tags": [ "adguard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(adguard_num_dns_queries, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "AdGuard Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing TIme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_avg_processing_time{hostname=~'$node'}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "adguard_top_blocked_domains{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top clients by source",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "adguard_top_clients{hostname=~'$node'}",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top clients",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "adguard_top_clients{hostname=~'$node'}",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "adguard_top_queried_domains{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "adguard_top_blocked_domains{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  }
 ]
}